// Tinedy CRM Seed Data Script
// Generated by Database Agent (Alex)

import { PrismaClient } from '@prisma/client';
import SeedDataGenerator, { SEED_DATA, SeedDataConfig } from '../lib/utils/seed-generators';

const prisma = new PrismaClient();

// Configuration สำหรับ seed data
const SEED_CONFIG: SeedDataConfig = {
  users: 8,           // จำนวนผู้ใช้
  customers: 15,      // จำนวนลูกค้า
  jobs: 25,           // จำนวนงาน
  qualityChecklists: 5, // จำนวน quality checklists
  cleanExisting: true   // ล้างข้อมูลเก่า
};

async function main() {
  console.log('🌱 Starting Tinedy CRM seed data generation...\n');

  try {
    // ล้างข้อมูลเก่า (ถ้า config เปิด)
    if (SEED_CONFIG.cleanExisting) {
      await cleanExistingData();
    }

    // สร้างข้อมูลใหม่
    const users = await createUsers();
    const customers = await createCustomers();
    const qualityChecklists = await createQualityChecklists();
    const jobs = await createJobs(customers, users);
    const qualityChecks = await createQualityChecks(jobs, qualityChecklists);
    const trainingWorkflows = await createTrainingWorkflows(jobs);
    const webhookLogs = await createWebhookLogs(jobs);
    const auditLogs = await createAuditLogs(customers, jobs, users);

    // สรุปผล
    printSummary({
      users: users.length,
      customers: customers.length,
      qualityChecklists: qualityChecklists.length,
      jobs: jobs.length,
      qualityChecks: qualityChecks.length,
      trainingWorkflows: trainingWorkflows.length,
      webhookLogs: webhookLogs.length,
      auditLogs: auditLogs.length
    });

  } catch (error) {
    console.error('❌ Error during seed data generation:', error);
    throw error;
  }
}

async function cleanExistingData() {
  console.log('🧹 Cleaning existing data...');

  // ลบข้อมูลเรียงตาม dependencies
  await prisma.auditLog.deleteMany();
  await prisma.webhookLog.deleteMany();
  await prisma.trainingWorkflow.deleteMany();
  await prisma.qualityCheck.deleteMany();
  await prisma.job.deleteMany();
  await prisma.qualityChecklist.deleteMany();
  await prisma.customer.deleteMany();
  await prisma.user.deleteMany();

  console.log('✅ Existing data cleaned\n');
}

async function createUsers() {
  console.log('👥 Creating users...');

  const users = [];
  const roles = ['ADMIN', 'OPERATIONS', 'TRAINING', 'QC_MANAGER'] as const;

  // สร้าง Admin user
  const adminUser = await prisma.user.create({
    data: {
      id: SeedDataGenerator.generateId('admin-'),
      email: 'admin@tinedy.com',
      name: 'ผู้ดูแลระบบ',
      role: 'ADMIN',
      isActive: true
    }
  });
  users.push(adminUser);

  // สร้าง users อื่นๆ
  for (let i = 0; i < SEED_CONFIG.users - 1; i++) {
    const userName = SeedDataGenerator.randomFrom(SEED_DATA.userNames);
    const role = SeedDataGenerator.randomFrom(roles);

    const user = await prisma.user.create({
      data: {
        id: SeedDataGenerator.generateId('user-'),
        email: SeedDataGenerator.generateEmail(userName),
        name: userName,
        role: role,
        isActive: Math.random() > 0.1 // 90% active
      }
    });
    users.push(user);
  }

  console.log(`✅ Created ${users.length} users`);
  return users;
}

async function createCustomers() {
  console.log('🏢 Creating customers...');

  const customers = [];
  const statuses = ['ACTIVE', 'INACTIVE', 'BLOCKED'] as const;

  for (let i = 0; i < SEED_CONFIG.customers; i++) {
    const companyName = SeedDataGenerator.randomFrom(SEED_DATA.companyNames);
    const status = i < SEED_CONFIG.customers * 0.8 ? 'ACTIVE' :
                  SeedDataGenerator.randomFrom(statuses);

    const customer = await prisma.customer.create({
      data: {
        id: SeedDataGenerator.generateId('customer-'),
        lineUserId: SeedDataGenerator.generateLineUserId(),
        name: companyName,
        phone: SeedDataGenerator.generatePhoneNumber(),
        email: SeedDataGenerator.generateEmail(companyName),
        address: SeedDataGenerator.randomFrom(SEED_DATA.addresses),
        notes: Math.random() > 0.5 ?
               `ลูกค้า${status === 'ACTIVE' ? 'ดี' : 'ปัญหา'} - ต้องการ${SeedDataGenerator.randomFrom(['การติดตาม', 'ความระมัดระวัง', 'บริการพิเศษ'])}` :
               null,
        status: status
      }
    });
    customers.push(customer);
  }

  console.log(`✅ Created ${customers.length} customers`);
  return customers;
}

async function createQualityChecklists() {
  console.log('📋 Creating quality checklists...');

  const checklists = [];
  const checklistTemplates = [
    {
      name: 'มาตรฐานการให้บริการทั่วไป',
      description: 'เช็คลิสต์มาตรฐานสำหรับการให้บริการทุกประเภท',
      serviceType: 'general'
    },
    {
      name: 'มาตรฐานการปรึกษาระบบ IT',
      description: 'เช็คลิสต์เฉพาะสำหรับงานปรึกษาด้าน IT',
      serviceType: 'การปรึกษาระบบ IT'
    },
    {
      name: 'มาตรฐานการฝึกอบรม',
      description: 'เช็คลิสต์สำหรับงานฝึกอบรมพนักงาน',
      serviceType: 'การฝึกอบรมพนักงาน'
    },
    {
      name: 'มาตรฐานการตรวจสอบคุณภาพ',
      description: 'เช็คลิสต์สำหรับงานตรวจสอบและประเมินคุณภาพ',
      serviceType: 'การตรวจสอบและประเมินคุณภาพ'
    },
    {
      name: 'มาตรฐานการติดตั้งระบบ',
      description: 'เช็คลิสต์สำหรับงานติดตั้งระบบและอุปกรณ์',
      serviceType: 'การติดตั้งระบบความปลอดภัย'
    }
  ];

  for (const template of checklistTemplates) {
    const items = SeedDataGenerator.generateQualityCheckItems(template.serviceType);

    const checklist = await prisma.qualityChecklist.create({
      data: {
        id: SeedDataGenerator.generateId('checklist-'),
        name: template.name,
        description: template.description,
        items: items,
        isActive: true
      }
    });
    checklists.push(checklist);
  }

  console.log(`✅ Created ${checklists.length} quality checklists`);
  return checklists;
}

async function createJobs(customers: any[], users: any[]) {
  console.log('💼 Creating jobs...');

  const jobs = [];
  const statuses = ['NEW', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'ON_HOLD'] as const;
  const priorities = ['LOW', 'MEDIUM', 'HIGH', 'URGENT'] as const;
  const operationsUsers = users.filter(u => ['OPERATIONS', 'ADMIN'].includes(u.role));

  for (let i = 0; i < SEED_CONFIG.jobs; i++) {
    const customer = SeedDataGenerator.randomFrom(customers.filter(c => c.status === 'ACTIVE'));
    const serviceType = SeedDataGenerator.randomFrom(SEED_DATA.serviceTypes);
    const status = SeedDataGenerator.randomFrom(statuses);
    const priority = SeedDataGenerator.randomFrom(priorities);
    const assignedTo = Math.random() > 0.3 ? SeedDataGenerator.randomFrom(operationsUsers) : null;

    // คำนวณวันที่ตาม status
    let scheduledAt = null;
    let completedAt = null;

    if (status !== 'NEW') {
      scheduledAt = SeedDataGenerator.pastDateRange(14); // จองไว้ใน 2 สัปดาห์ที่ผ่านมา
    } else {
      scheduledAt = SeedDataGenerator.futureDateRange(14); // จองไว้ใน 2 สัปดาห์ข้างหน้า
    }

    if (status === 'COMPLETED') {
      completedAt = SeedDataGenerator.pastDateRange(7); // เสร็จใน 1 สัปดาห์ที่ผ่านมา
    }

    const job = await prisma.job.create({
      data: {
        id: SeedDataGenerator.generateId('job-'),
        customerId: customer.id,
        assignedToId: assignedTo?.id || null,
        serviceType: serviceType,
        description: SeedDataGenerator.generateJobDescription(serviceType, customer.name),
        status: status,
        priority: priority,
        scheduledAt: scheduledAt,
        completedAt: completedAt,
        n8nWorkflowId: `workflow-${Math.floor(Math.random() * 1000)}`,
        webhookData: null // จะเพิ่มทีหลังใน webhook logs
      }
    });
    jobs.push(job);
  }

  console.log(`✅ Created ${jobs.length} jobs`);
  return jobs;
}

async function createQualityChecks(jobs: any[], qualityChecklists: any[]) {
  console.log('✅ Creating quality checks...');

  const qualityChecks = [];
  const qcStatuses = ['PENDING', 'IN_PROGRESS', 'PASSED', 'FAILED', 'NEEDS_REVIEW'] as const;
  const qcUsers = await prisma.user.findMany({
    where: { role: { in: ['QC_MANAGER', 'ADMIN'] } }
  });

  // สร้าง quality check สำหรับงานที่ IN_PROGRESS หรือ COMPLETED
  const eligibleJobs = jobs.filter(j => ['IN_PROGRESS', 'COMPLETED'].includes(j.status));

  for (const job of eligibleJobs) {
    // หา checklist ที่เหมาะสม
    let checklist = qualityChecklists.find(c =>
      c.name.includes(job.serviceType) ||
      c.description?.includes(job.serviceType)
    );

    if (!checklist) {
      checklist = qualityChecklists.find(c => c.name.includes('ทั่วไป'));
    }

    const qcStatus = job.status === 'COMPLETED' ?
                    SeedDataGenerator.randomFrom(['PASSED', 'FAILED', 'NEEDS_REVIEW']) :
                    SeedDataGenerator.randomFrom(['PENDING', 'IN_PROGRESS']);

    const completedBy = qcStatus === 'PENDING' ? null :
                       SeedDataGenerator.randomFrom(qcUsers)?.id;

    const completedAt = completedBy ? SeedDataGenerator.pastDateRange(3) : null;

    const notes = qcStatus === 'FAILED' ?
                  'พบข้อบกพร่องในการให้บริการ ต้องปรับปรุง' :
                  qcStatus === 'PASSED' ?
                  'ผ่านการตรวจสอบคุณภาพเรียบร้อย' :
                  qcStatus === 'NEEDS_REVIEW' ?
                  'ต้องการการทบทวนเพิ่มเติม' :
                  null;

    const qualityCheck = await prisma.qualityCheck.create({
      data: {
        id: SeedDataGenerator.generateId('qc-'),
        jobId: job.id,
        checklistId: checklist.id,
        status: qcStatus,
        completedBy: completedBy,
        completedAt: completedAt,
        notes: notes
      }
    });
    qualityChecks.push(qualityCheck);
  }

  console.log(`✅ Created ${qualityChecks.length} quality checks`);
  return qualityChecks;
}

async function createTrainingWorkflows(jobs: any[]) {
  console.log('🎓 Creating training workflows...');

  const trainingWorkflows = [];
  const trainingStatuses = [
    'AWAITING_DOCUMENTS', 'DOCUMENTS_RECEIVED',
    'TRAINING_IN_PROGRESS', 'TRAINING_COMPLETED', 'COMPLETED'
  ] as const;

  // สร้าง training workflow สำหรับงานฝึกอบรม
  const trainingJobs = jobs.filter(j => j.serviceType.includes('ฝึกอบรม'));

  for (const job of trainingJobs) {
    const status = job.status === 'COMPLETED' ?
                  SeedDataGenerator.randomFrom(['TRAINING_COMPLETED', 'COMPLETED']) :
                  job.status === 'IN_PROGRESS' ?
                  SeedDataGenerator.randomFrom(['DOCUMENTS_RECEIVED', 'TRAINING_IN_PROGRESS']) :
                  'AWAITING_DOCUMENTS';

    const documentsReceived = !['AWAITING_DOCUMENTS'].includes(status);
    const trainingCompleted = ['TRAINING_COMPLETED', 'COMPLETED'].includes(status);

    const notes = status === 'COMPLETED' ?
                  'การฝึกอบรมเสร็จสิ้นเรียบร้อย ผลการประเมินดีมาก' :
                  status === 'TRAINING_IN_PROGRESS' ?
                  'อยู่ระหว่างการฝึกอบรม คาดว่าจะเสร็จในสัปดาห์หน้า' :
                  status === 'DOCUMENTS_RECEIVED' ?
                  'ได้รับเอกสารเรียบร้อย เตรียมเริ่มอบรม' :
                  null;

    const trainingWorkflow = await prisma.trainingWorkflow.create({
      data: {
        id: SeedDataGenerator.generateId('training-'),
        jobId: job.id,
        status: status,
        documentsReceived: documentsReceived,
        trainingCompleted: trainingCompleted,
        notes: notes
      }
    });
    trainingWorkflows.push(trainingWorkflow);
  }

  console.log(`✅ Created ${trainingWorkflows.length} training workflows`);
  return trainingWorkflows;
}

async function createWebhookLogs(jobs: any[]) {
  console.log('📡 Creating webhook logs...');

  const webhookLogs = [];
  const webhookStatuses = ['RECEIVED', 'PROCESSING', 'PROCESSED', 'FAILED', 'RETRY_NEEDED'] as const;

  // สร้าง webhook log สำหรับงานที่สร้างจาก N8N
  for (const job of jobs) {
    const customer = await prisma.customer.findUnique({
      where: { id: job.customerId }
    });

    if (!customer) continue;

    const status = Math.random() > 0.1 ? 'PROCESSED' :
                  SeedDataGenerator.randomFrom(['FAILED', 'RETRY_NEEDED']);

    const processedAt = status === 'PROCESSED' ?
                       SeedDataGenerator.pastDateRange(1) : null;

    const errorMessage = status === 'FAILED' ?
                        'Customer creation failed due to invalid LINE user ID' :
                        status === 'RETRY_NEEDED' ?
                        'Database connection timeout - scheduled for retry' :
                        null;

    const retryCount = ['FAILED', 'RETRY_NEEDED'].includes(status) ?
                      Math.floor(Math.random() * 3) : 0;

    const payload = SeedDataGenerator.generateWebhookPayload(customer, job);

    const webhookLog = await prisma.webhookLog.create({
      data: {
        id: SeedDataGenerator.generateId('webhook-'),
        source: 'N8N',
        workflowId: job.n8nWorkflowId,
        executionId: `exec-${Math.floor(Math.random() * 10000)}`,
        payload: payload,
        status: status,
        processedAt: processedAt,
        errorMessage: errorMessage,
        createdJobId: status === 'PROCESSED' ? job.id : null,
        retryCount: retryCount
      }
    });
    webhookLogs.push(webhookLog);
  }

  console.log(`✅ Created ${webhookLogs.length} webhook logs`);
  return webhookLogs;
}

async function createAuditLogs(customers: any[], jobs: any[], users: any[]) {
  console.log('📋 Creating audit logs...');

  const auditLogs = [];
  const actions = ['CREATE', 'UPDATE', 'DELETE'] as const;
  const entityTypes = ['Customer', 'Job', 'User'] as const;

  // สร้าง audit logs สำหรับการกระทำต่างๆ
  const entities = [
    ...customers.map(c => ({ type: 'Customer', entity: c })),
    ...jobs.map(j => ({ type: 'Job', entity: j })),
    ...users.map(u => ({ type: 'User', entity: u }))
  ];

  for (let i = 0; i < Math.min(50, entities.length); i++) {
    const { type, entity } = SeedDataGenerator.randomFrom(entities);
    const action = SeedDataGenerator.randomFrom(actions);
    const user = SeedDataGenerator.randomFrom(users);

    const oldValues = action === 'CREATE' ? null : {
      name: entity.name,
      status: entity.status,
      updatedAt: SeedDataGenerator.pastDateRange(7)
    };

    const newValues = action === 'DELETE' ? null : {
      name: entity.name,
      status: entity.status,
      updatedAt: new Date()
    };

    const auditLog = await prisma.auditLog.create({
      data: {
        id: SeedDataGenerator.generateId('audit-'),
        entityType: type,
        entityId: entity.id,
        action: action,
        oldValues: oldValues,
        newValues: newValues,
        userId: user.id,
        timestamp: SeedDataGenerator.pastDateRange(30)
      }
    });
    auditLogs.push(auditLog);
  }

  console.log(`✅ Created ${auditLogs.length} audit logs`);
  return auditLogs;
}

function printSummary(counts: Record<string, number>) {
  console.log('\n🎉 Seed data generation completed successfully!');
  console.log('📊 Summary:');
  console.log('='.repeat(40));

  Object.entries(counts).forEach(([key, count]) => {
    const emoji = {
      users: '👥',
      customers: '🏢',
      qualityChecklists: '📋',
      jobs: '💼',
      qualityChecks: '✅',
      trainingWorkflows: '🎓',
      webhookLogs: '📡',
      auditLogs: '📋'
    }[key] || '📌';

    console.log(`   ${emoji} ${key}: ${count}`);
  });

  console.log('='.repeat(40));
  console.log('🚀 Tinedy CRM is ready for development and testing!');
}

// Execute seed script
main()
  .catch((e) => {
    console.error('❌ Seed script failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });