// Security Status API Endpoint
// Generated by Database Agent (Alex)

import { NextRequest, NextResponse } from 'next/server';
import { requirePermission } from '@/lib/middleware/auth-utils';
import { securityDashboard } from '@/lib/monitoring/security-dashboard';
import { securityMonitor } from '@/lib/monitoring/security-monitor';

/**
 * GET /api/security/status
 * Get real-time security status
 */
@requirePermission('admin', 'read')
export async function GET(request: NextRequest) {
  try {
    const status = await securityDashboard.getSecurityStatus();

    return NextResponse.json(status);

  } catch (error) {
    console.error('Security status error:', error);
    return NextResponse.json(
      { error: 'Failed to fetch security status' },
      { status: 500 }
    );
  }
}

/**
 * GET /api/security/metrics
 * Get security metrics
 */
@requirePermission('admin', 'read')
export async function metrics(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url);
    const hours = parseInt(searchParams.get('hours') || '24');

    const metrics = await securityMonitor.getSecurityMetrics(hours);

    return NextResponse.json(metrics);

  } catch (error) {
    console.error('Security metrics error:', error);
    return NextResponse.json(
      { error: 'Failed to fetch security metrics' },
      { status: 500 }
    );
  }
}