// N8N Webhook Data Types for Tinedy CRM
// Generated by Database Agent (Alex)

export interface N8NWebhookPayload {
  // ข้อมูล N8N Workflow
  workflow: {
    id: string;
    name: string;
    executionId: string;
    timestamp: string;
  };

  // ข้อมูลลูกค้าจาก LINE OA
  customer: {
    lineUserId: string;        // รหัสผู้ใช้ LINE
    displayName: string;       // ชื่อที่แสดงใน LINE
    phone?: string;            // เบอร์โทรศัพท์ (ถ้ามี)
    email?: string;            // อีเมล (ถ้ามี)
    pictureUrl?: string;       // รูปโปรไฟล์ LINE
    language?: string;         // ภาษาที่ใช้
    statusMessage?: string;    // สถานะข้อความ LINE
  };

  // ข้อมูลการจองบริการ
  booking: {
    serviceType: string;       // ประเภทบริการ
    description: string;       // รายละเอียดงาน
    preferredDate?: string;    // วันที่ต้องการ (ISO string)
    priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT';
    location?: string;         // สถานที่
    specialRequirements?: string; // ความต้องการพิเศษ
    estimatedDuration?: number;   // ระยะเวลาโดยประมาณ (นาที)
    budget?: number;           // งบประมาณ
  };

  // ข้อมูลบริบทการสนทนา
  conversation: {
    messageId: string;         // รหัสข้อความ
    messageType: 'text' | 'image' | 'audio' | 'video' | 'file' | 'location' | 'sticker';
    messageText?: string;      // ข้อความ
    replyToken?: string;       // token สำหรับตอบกลับ
    timestamp: string;         // เวลาที่ส่งข้อความ
  };

  // ข้อมูลเพิ่มเติม
  metadata: {
    source: 'LINE_OA';         // แหล่งที่มาข้อมูล
    channelId: string;         // รหัสช่องทาง LINE
    webhookEventType: string;  // ประเภท event เช่น 'message', 'follow'
    userAgent?: string;        // User agent
    ipAddress?: string;        // IP address
    rawPayload?: any;          // ข้อมูลดิบทั้งหมด (สำหรับ debug)
  };
}

// Response type สำหรับ webhook processing
export interface WebhookProcessingResult {
  success: boolean;
  data?: {
    customerId: string;
    jobId: string;
    status: 'created' | 'updated' | 'duplicate';
  };
  error?: {
    code: string;
    message: string;
    details?: any;
  };
  warnings?: string[];
}

// Type สำหรับ webhook validation
export interface WebhookValidationResult {
  isValid: boolean;
  errors: string[];
  warnings: string[];
}

// Type สำหรับ customer data transformation
export interface CustomerDataInput {
  lineUserId: string;
  name: string;
  phone?: string;
  email?: string;
  metadata?: {
    pictureUrl?: string;
    language?: string;
    statusMessage?: string;
  };
}

// Type สำหรับ job creation
export interface JobCreateInput {
  customerId: string;
  serviceType: string;
  description: string;
  priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT';
  scheduledAt?: Date;
  webhookData: N8NWebhookPayload;
  n8nWorkflowId: string;
}

// Type สำหรับ webhook authentication
export interface WebhookAuthHeaders {
  'x-n8n-signature'?: string;
  'x-timestamp'?: string;
  'x-workflow-id'?: string;
  'authorization'?: string;
}

// Type สำหรับ retry configuration
export interface RetryConfig {
  maxRetries: number;
  retryDelays: number[];      // milliseconds
  retryableErrors: string[];
  exponentialBackoff: boolean;
}

// Enum สำหรับ webhook processing status
export enum WebhookProcessingStatus {
  RECEIVED = 'RECEIVED',
  VALIDATING = 'VALIDATING',
  PROCESSING = 'PROCESSING',
  CREATING_CUSTOMER = 'CREATING_CUSTOMER',
  CREATING_JOB = 'CREATING_JOB',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  RETRY_NEEDED = 'RETRY_NEEDED'
}

// Error codes สำหรับ webhook processing
export enum WebhookErrorCode {
  INVALID_PAYLOAD = 'INVALID_PAYLOAD',
  MISSING_REQUIRED_FIELDS = 'MISSING_REQUIRED_FIELDS',
  CUSTOMER_CREATION_FAILED = 'CUSTOMER_CREATION_FAILED',
  JOB_CREATION_FAILED = 'JOB_CREATION_FAILED',
  DATABASE_ERROR = 'DATABASE_ERROR',
  AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  DUPLICATE_REQUEST = 'DUPLICATE_REQUEST'
}