// Seed Data Generators for Tinedy CRM
// Generated by Database Agent (Alex)

export interface SeedDataConfig {
  users: number;
  customers: number;
  jobs: number;
  qualityChecklists: number;
  cleanExisting: boolean;
}

// ข้อมูลพื้นฐานสำหรับสร้าง seed data
export const SEED_DATA = {
  // ชื่อบริษัทไทย
  companyNames: [
    'บริษัท เทคโนโลยี อินโนเวชั่น จำกัด',
    'ห้างหุ้นส่วน สมาร์ท โซลูชั่น',
    'บริษัท ดิจิทัล ทรานส์ฟอร์เมชั่น จำกัด (มหาชน)',
    'ร้านค้าปลีก โมเดิร์น มาร์เก็ต',
    'โรงงาน อุตสาหกรรม เซฟตี้ เฟิร์สท์',
    'บริษัท เอ็นเนอร์จี้ กรีน เพาเวอร์ จำกัด',
    'ห้างหุ้นส่วน คลาวด์ เซอร์วิส โปรไวเดอร์',
    'บริษัท ฟูด แอนด์ เบเวอเรจ อินดัสทรี่ จำกัด',
    'โรงแรม ลักชูรี่ รีสอร์ท แอนด์ สปา',
    'บริษัท ลอจิสติกส์ แอนด์ ซัพพลาย เชน จำกัด',
    'ห้างหุ้นส่วน ฟินเทค อินโนเวชั่น',
    'บริษัท อี-คอมเมิร์ซ แพลตฟอร์ม จำกัด',
    'โรงงาน ออโตโมทีฟ พาร์ท แมนูแฟคเจอร์',
    'บริษัท เฮลท์แคร์ เทคโนโลยี่ จำกัด',
    'ห้างหุ้นส่วน ไฟแนนเชียล คอนซัลติ้ง'
  ],

  // ประเภทบริการ
  serviceTypes: [
    'การปรึกษาระบบ IT',
    'การฝึกอบรมพนักงาน',
    'การตรวจสอบและประเมินคุณภาพ',
    'การติดตั้งระบบความปลอดภัย',
    'การพัฒนาซอฟต์แวร์',
    'การจัดการโครงการ',
    'การวิเคราะห์ข้อมูล',
    'การออกแบบระบบ',
    'การบำรุงรักษาระบบ',
    'การย้ายข้อมูล',
    'การปรับปรุงประสิทธิภาพ',
    'การตรวจสอบความปลอดภัย'
  ],

  // ชื่อผู้ใช้
  userNames: [
    'สมชาย วงศ์สกุล',
    'วิภาวี เจริญสุข',
    'ธนากร มั่งคั่ง',
    'สุมาลี สง่างาม',
    'ประวิทย์ ชาญชัย',
    'อัญชลี ปัญญาดี',
    'วีระพงษ์ กล้าหาญ',
    'พิมพ์ชนก ใจดี',
    'นันทวัฒน์ เก่งกาจ',
    'กัญญาณี สุขสำราญ',
    'อานนท์ รุ่งเรือง',
    'มนัสวี สว่างใส'
  ],

  // อีเมลโดเมน
  emailDomains: [
    'company.co.th',
    'business.com',
    'enterprise.net',
    'corporation.org',
    'industry.co.th',
    'services.com'
  ],

  // เบอร์โทรศัพท์ prefix
  phonePrefix: [
    '+66-2', // กรุงเทพฯ
    '+66-32', // นนทบุรี
    '+66-33', // ปทุมธานี
    '+66-34', // สมุทรปราการ
    '+66-35', // ราชบุรี
    '+66-38', // ชลบุรี
    '+66-44', // อุดรธานี
    '+66-53', // เชียงใหม่
    '+66-74', // สุราษฎร์ธานี
    '+66-81', // มือถือ
    '+66-82', // มือถือ
    '+66-83'  // มือถือ
  ],

  // ที่อยู่
  addresses: [
    '123 ถนนสุขุมวิท แขวงคลองเตย เขตคลองเตย กรุงเทพฯ 10110',
    '456 ถนนพหลโยธิน แขวงสามเสนใน เขตพญาไท กรุงเทพฯ 10400',
    '789 ถนนรามคำแหง แขวงหัวหมาก เขตบางกะปิ กรุงเทพฯ 10240',
    '321 ถนนเพชรบุรี แขวงมักกะสัน เขตราชเทวี กรุงเทพฯ 10400',
    '654 ถนนสีลม แขวงสีลม เขตบางรัก กรุงเทพฯ 10500',
    '987 ถนนลาดพร้าว แขวงจอมพล เขตจตุจักร กรุงเทพฯ 10900',
    '147 ถนนจรัญสนิทวงศ์ แขวงบางแค เขตบางแค กรุงเทพฯ 10160',
    '258 ถนนกิ่งแก้ว ตำบลราชาเทวะ อำเภอบางพลี สมุทรปราการ 10540',
    '369 ถนนประชาอุทิศ แขวงทุ่งครุ เขตทุ่งครุ กรุงเทพฯ 10140',
    '741 ถนนติวานนท์ ตำบลตลาดขวัญ อำเภอเมือง นนทบุรี 11000'
  ]
};

// ฟังก์ชัน Utility สำหรับสร้างข้อมูล
export class SeedDataGenerator {

  /**
   * สุ่มเลือกจาก array
   */
  static randomFrom<T>(array: T[]): T {
    return array[Math.floor(Math.random() * array.length)];
  }

  /**
   * สุ่มเลือกหลายตัวจาก array
   */
  static randomMultipleFrom<T>(array: T[], count: number): T[] {
    const shuffled = [...array].sort(() => 0.5 - Math.random());
    return shuffled.slice(0, count);
  }

  /**
   * สร้าง LINE User ID
   */
  static generateLineUserId(): string {
    const chars = '0123456789abcdef';
    let result = 'U';
    for (let i = 0; i < 32; i++) {
      result += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    return result;
  }

  /**
   * สร้างเบอร์โทรศัพท์
   */
  static generatePhoneNumber(): string {
    const prefix = this.randomFrom(SEED_DATA.phonePrefix);
    const number = Math.floor(Math.random() * 9000000) + 1000000;
    const formatted = number.toString();
    return `${prefix}-${formatted.slice(0, 3)}-${formatted.slice(3)}`;
  }

  /**
   * สร้างอีเมล
   */
  static generateEmail(name: string): string {
    const cleanName = name
      .replace(/[ก-๙]/g, '') // Remove Thai characters
      .replace(/\s+/g, '')
      .toLowerCase();

    const username = cleanName || `user${Math.floor(Math.random() * 1000)}`;
    const domain = this.randomFrom(SEED_DATA.emailDomains);
    return `${username}@${domain}`;
  }

  /**
   * สร้างวันที่สุ่ม
   */
  static randomDate(start: Date, end: Date): Date {
    return new Date(start.getTime() + Math.random() * (end.getTime() - start.getTime()));
  }

  /**
   * สร้างวันที่ในอนาคต
   */
  static futureDateRange(daysFromNow: number = 30): Date {
    const now = new Date();
    const future = new Date(now.getTime() + daysFromNow * 24 * 60 * 60 * 1000);
    return this.randomDate(now, future);
  }

  /**
   * สร้างวันที่ในอดีต
   */
  static pastDateRange(daysAgo: number = 30): Date {
    const now = new Date();
    const past = new Date(now.getTime() - daysAgo * 24 * 60 * 60 * 1000);
    return this.randomDate(past, now);
  }

  /**
   * สร้าง CUID สำหรับ ID
   */
  static generateId(prefix: string = ''): string {
    const timestamp = Date.now().toString(36);
    const randomPart = Math.random().toString(36).substr(2, 9);
    return `${prefix}${timestamp}${randomPart}`;
  }

  /**
   * สร้างรายการ Quality Check items
   */
  static generateQualityCheckItems(serviceType: string): any[] {
    const baseItems = [
      { item: 'ตรวจสอบความถูกต้องของข้อมูลลูกค้า', required: true },
      { item: 'ยืนยันความต้องการของลูกค้า', required: true },
      { item: 'ประเมินความพึงพอใจของลูกค้า', required: true }
    ];

    const serviceSpecificItems: Record<string, any[]> = {
      'การปรึกษาระบบ IT': [
        { item: 'วิเคราะห์ระบบปัจจุบัน', required: true },
        { item: 'เสนอแนะการปรับปรุง', required: true },
        { item: 'จัดทำเอกสารสรุปผล', required: false }
      ],
      'การฝึกอบรมพนักงาน': [
        { item: 'เตรียมเอกสารการอบรม', required: true },
        { item: 'ดำเนินการอบรมตามหลักสูตร', required: true },
        { item: 'ประเมินผลการอบรม', required: true },
        { item: 'ออกใบประกาศนียบัตร', required: false }
      ],
      'การตรวจสอบและประเมินคุณภาพ': [
        { item: 'ตรวจสอบตามมาตรฐาน', required: true },
        { item: 'บันทึกผลการตรวจสอบ', required: true },
        { item: 'เสนอแนะการแก้ไข', required: false }
      ]
    };

    const specificItems = serviceSpecificItems[serviceType] || [];
    return [...baseItems, ...specificItems];
  }

  /**
   * สร้างข้อมูล N8N Webhook payload
   */
  static generateWebhookPayload(customer: any, job: any): any {
    return {
      workflow: {
        id: `workflow-${Math.floor(Math.random() * 1000)}`,
        name: 'LINE OA Booking Processor',
        executionId: `exec-${Math.floor(Math.random() * 10000)}`,
        timestamp: new Date().toISOString()
      },
      customer: {
        lineUserId: customer.lineUserId,
        displayName: customer.name,
        phone: customer.phone,
        email: customer.email
      },
      booking: {
        serviceType: job.serviceType,
        description: job.description,
        priority: job.priority,
        preferredDate: job.scheduledAt?.toISOString()
      },
      conversation: {
        messageId: `msg-${Math.floor(Math.random() * 10000)}`,
        messageType: 'text' as const,
        messageText: `ต้องการจองบริการ ${job.serviceType}`,
        timestamp: new Date().toISOString()
      },
      metadata: {
        source: 'LINE_OA' as const,
        channelId: 'channel-tinedy-crm',
        webhookEventType: 'message',
        ipAddress: `192.168.1.${Math.floor(Math.random() * 255)}`
      }
    };
  }

  /**
   * สร้างรายละเอียดงาน
   */
  static generateJobDescription(serviceType: string, customerName: string): string {
    const descriptions: Record<string, string[]> = {
      'การปรึกษาระบบ IT': [
        `วิเคราะห์และประเมินระบบ IT ปัจจุบันของ ${customerName}`,
        `ให้คำปรึกษาการปรับปรุงระบบเทคโนโลยีสำหรับ ${customerName}`,
        `ออกแบบ architecture ระบบใหม่สำหรับ ${customerName}`
      ],
      'การฝึกอบรมพนักงาน': [
        `จัดอบรมพนักงานเรื่องระบบการจัดการคุณภาพสำหรับ ${customerName}`,
        `อบรมทีมงานด้านความปลอดภัยไซเบอร์ให้กับ ${customerName}`,
        `พัฒนาทักษะการใช้งานซอฟต์แวร์ใหม่สำหรับพนักงาน ${customerName}`
      ],
      'การตรวจสอบและประเมินคุณภาพ': [
        `ตรวจสอบระบบการจัดการคุณภาพของ ${customerName}`,
        `ประเมินกระบวนการผลิตและควบคุมคุณภาพที่ ${customerName}`,
        `ตรวจสอบมาตรฐาน ISO และเสนอแนะการปรับปรุงสำหรับ ${customerName}`
      ]
    };

    const options = descriptions[serviceType] || [
      `ให้บริการ ${serviceType} สำหรับ ${customerName}`,
      `ดำเนินการ ${serviceType} ตามความต้องการของ ${customerName}`
    ];

    return this.randomFrom(options);
  }

  /**
   * คำนวณราคาประมาณ
   */
  static calculateEstimatedPrice(serviceType: string, priority: string): number {
    const basePrices: Record<string, number> = {
      'การปรึกษาระบบ IT': 50000,
      'การฝึกอบรมพนักงาน': 30000,
      'การตรวจสอบและประเมินคุณภาพ': 40000,
      'การติดตั้งระบบความปลอดภัย': 80000,
      'การพัฒนาซอฟต์แวร์': 100000
    };

    const priorityMultiplier: Record<string, number> = {
      'LOW': 0.8,
      'MEDIUM': 1.0,
      'HIGH': 1.3,
      'URGENT': 1.6
    };

    const basePrice = basePrices[serviceType] || 25000;
    const multiplier = priorityMultiplier[priority] || 1.0;

    return Math.round(basePrice * multiplier);
  }
}

export default SeedDataGenerator;