markdownExploder: true
qa:
  qaLocation: docs/qa
prd:
  prdFile: docs/prd.md
  prdVersion: v4
  prdSharded: false
  prdShardedLocation: docs/prd
  epicFilePattern: epic-{n}*.md
architecture:
  architectureFile: docs/architecture.md
  architectureVersion: v4
  architectureSharded: false
  architectureShardedLocation: docs/architecture
customTechnicalDocuments: null
devLoadAlwaysFiles:
  - docs/architecture/coding-standards.md
  - docs/architecture/tech-stack.md
  - docs/architecture/source-tree.md
devDebugLog: .ai/debug-log.md
devStoryLocation: docs/stories
slashPrefix: BMad
agents:
  - db
  - database-architect
  - nextjs
  - auth
  - test
  - api
  - deployment-specialist
  - auto-coordinator
  - ux-ui-designer
  - qa-engineer
  - business-analyst
  - product-manager
  - data-engineer
  - performance-engineer
  - technical-writer
  - integration-specialist
  - mobile-developer
  - customer-success
autoDelegation:
  enabled: true
  defaultCoordinator: bmad-orchestrator
  escalationAgent: product-manager
  delegationRules:
    database: database-architect
    schema: database-architect
    migration: database-architect
    prisma: database-architect
    component: nextjs
    page: nextjs
    api: api
    route: nextjs
    react: nextjs
    nextjs: nextjs
    frontend: nextjs
    backend: nextjs
    auth: auth
    login: auth
    security: auth
    permission: auth
    role: auth
    nextauth: auth
    test: test
    testing: test
    qa: qa-engineer
    quality: qa-engineer
    bug: qa-engineer
    validation: qa-engineer
    integration: api
    webhook: api
    n8n: api
    external: api
    deploy: deployment-specialist
    deployment: deployment-specialist
    cicd: deployment-specialist
    build: deployment-specialist
    vercel: deployment-specialist
    production: deployment-specialist
    design: ux-ui-designer
    ux: ux-ui-designer
    ui: ux-ui-designer
    wireframe: ux-ui-designer
    interface: ux-ui-designer
    requirements: business-analyst
    process: business-analyst
    workflow: business-analyst
    business: business-analyst
    analysis: business-analyst
    product: product-manager
    strategy: product-manager
    roadmap: product-manager
    feature: product-manager
    prioritization: product-manager
    data: data-engineer
    analytics: data-engineer
    etl: data-engineer
    pipeline: data-engineer
    metrics: data-engineer
    reporting: data-engineer
    performance: performance-engineer
    optimization: performance-engineer
    slow: performance-engineer
    speed: performance-engineer
    bottleneck: performance-engineer
    memory: performance-engineer
    cpu: performance-engineer
    documentation: technical-writer
    docs: technical-writer
    manual: technical-writer
    guide: technical-writer
    tutorial: technical-writer
    training: technical-writer
    onboarding: technical-writer
    webhook: integration-specialist
    integration: integration-specialist
    sync: integration-specialist
    connect: integration-specialist
    bridge: integration-specialist
    mobile: mobile-developer
    app: mobile-developer
    ios: mobile-developer
    android: mobile-developer
    pwa: mobile-developer
    responsive: mobile-developer
    touch: mobile-developer
    user: customer-success
    adoption: customer-success
    training: customer-success
    support: customer-success
    feedback: customer-success
    satisfaction: customer-success
    success: customer-success
